language: cpp

dist: trusty
sudo: required

os:
    - linux
    # - osx

compiler:
    # - clang
    - gcc

env:
    # - TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
    # TODO build is taking too long, split even more, see script section
    - TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Unix Makefiles"


# matrix:
#     - exclude:
#         - os: osx
#           compiler: gcc
#     - allow_failures:
#         - os: osx
#         - compiler: clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            # - clang-3.5
            - g++-4.9
            - libxerces-c-dev
            - libxml2-dev
            - libxslt1-dev
            - xsltproc
            - libboost-all-dev
            - libncurses5-dev
            - libpython-dev
            - libxml2
            - libxml2-utils
            - mesa-common-dev

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt562-trusty -y
    - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
    - sudo apt-get update -qq

    # Update CMake.
    - wget --no-check-certificate http://www.cmake.org/files/v3.7/cmake-3.7.2-Linux-x86_64.tar.gz

    # Travis Qwt 6.0 does not cooperate with Qt5
    # We build and install those ourselves using Peacock.
    - git clone --recursive https://github.com/geoneric/peacock.git

install:
    - set -e

    - cd $TRAVIS_BUILD_DIR
    - pip install --user --upgrade pip
    - pip install --user --upgrade numpy
    - pip install --user --upgrade docopt
    - pip install --user --upgrade sphinx
    - pip install --user --upgrade pillow

    - sudo apt-get install qt56base
    - export PATH=/opt/qt56/bin:$PATH

    - sudo apt-get install gdal-bin libgdal-dev

    - mkdir $TRAVIS_BUILD_DIR/local

    - cd $TRAVIS_BUILD_DIR/local
    - tar zxf ../cmake-3.7.2-Linux-x86_64.tar.gz
    - export PATH=$TRAVIS_BUILD_DIR/local/cmake-3.7.2-Linux-x86_64/bin:$PATH

    - cd $TRAVIS_BUILD_DIR/peacock
    - export MAKEFLAGS='-j2'
    - mkdir build
    - cd build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 -Dpeacock_prefix=$TRAVIS_BUILD_DIR/local -Dbuild_qwt=true -Dqwt_version=6.1.2 ..
    - cmake --build . --target all

before_script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - cd $TRAVIS_BUILD_DIR/build
    - cmake -G"${TRAVIS_CMAKE_GENERATOR}" -DCMAKE_C_COMPILER=gcc-4.9 -DCMAKE_CXX_COMPILER=g++-4.9 -DPEACOCK_PREFIX:PATH=$TRAVIS_BUILD_DIR/local -DCMAKE_BUILD_TYPE=${TRAVIS_BUILD_TYPE} -DFERN_BUILD_ALGORITHM:BOOL=TRUE -DPCRASTER_BUILD_TEST:BOOL=TRUE ..

script:
    - set -e  # Don't run the tests if the build fails.
    - cd $TRAVIS_BUILD_DIR/build
    - export MAKEFLAGS='-j2'
    - python -c "import numpy as n; print(n.__version__); print(n.get_include());"
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target all

    - export MAKEFLAGS='-j1'
    - cmake --build . --config ${TRAVIS_BUILD_TYPE} --target test
    - cd ..

notifications:
    email:
        - k.dejong1@uu.nl
        - o.schmitz@uu.nl
